export const mcpServerPackageJsonContents = `{
  "name": "{{packageName}}",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {},
  "dependencies": {
    "{{#if runtime=bun}}@effect/platform-bun{{/if}}{{#if runtime=node}}@effect/platform-node{{/if}}": "4.0.0-rc.108",
    "effect": "4.0.0-rc.108"
  },
  "devDependencies": {
    "@repo/config-typescript": "{{workspaceDependency}}",
    "{{#if runtime=bun}}@types/bun{{/if}}{{#if runtime=node}}@types/node{{/if}}": "{{#if runtime=bun}}^1.2.17{{/if}}{{#if runtime=node}}^24.0.0{{/if}}",
    "vitest": "^4.1.4"
  }
}
`;

export const mcpServerTsconfigContents = `{
  "extends": "@repo/config-typescript/base.json",
  "compilerOptions": {
    "rootDir": "../..",
    "outDir": "dist",
    "noEmit": true,
    "types": ["{{#if runtime=bun}}bun{{/if}}{{#if runtime=node}}node{{/if}}"]
  },
  "include": ["src/**/*", "../../packages/ai/src/**/*"],
  "exclude": ["node_modules", "dist"]
}
`;

export const mcpServerIndexContents = `{{#if runtime=bun}}import { BunHttpServer, BunRuntime } from "@effect/platform-bun";{{/if}}{{#if runtime=node}}import { NodeHttpServer, NodeRuntime } from "@effect/platform-node";
import { createServer } from "node:http";{{/if}}
import { Config, Effect, Layer } from "effect";
import { McpProtocol, McpServer } from "effect/unstable/ai";
import { HttpRouter, HttpServer } from "effect/unstable/http";

export const McpServerConfig = Config.all({
  port: Config.number("MCP_PORT").pipe(Config.withDefault(9009)),
  hostname: Config.string("MCP_HOST").pipe(Config.withDefault("0.0.0.0")),
  allowedOrigins: Config.string("MCP_ALLOWED_ORIGINS").pipe(
    Config.withDefault("http://localhost:3000"),
  ),
});

// NOTE: Modules append tools, prompts, and resources to this layer.
const McpCapabilities = Layer.mergeAll(Layer.empty).pipe(
  Layer.satisfiesServicesType<never>(),
);

const McpHttpLive = Effect.gen(function* () {
  const config = yield* McpServerConfig;
  const allowedOrigins = config.allowedOrigins.split(",").map((origin) =>
    origin.trim(),
  );

  yield* Effect.logInfo("Starting MCP server at /mcp");

  return McpServer.layerHttp({
    name: "Stack Effect MCP Server",
    version: "0.1.0",
    path: "/mcp",
    protocols: [McpProtocol.v2025_06_18],
    allowedOrigins,
  }).pipe(
    Layer.provideMerge(McpCapabilities),
    HttpRouter.serve,
    HttpServer.withLogAddress,
    Layer.provide({{#if runtime=bun}}BunHttpServer.layerConfig(McpServerConfig){{/if}}{{#if runtime=node}}NodeHttpServer.layerConfig(createServer, McpServerConfig){{/if}}),
  );
}).pipe(
  Layer.unwrap,
  Layer.launch,
  Effect.satisfiesServicesType<never>(),
);

{{#if runtime=bun}}BunRuntime{{/if}}{{#if runtime=node}}NodeRuntime{{/if}}.runMain(McpHttpLive);
`;

export const mcpHelloPromptContents = `import { Effect, Layer, Schema } from "effect";
import { McpServer } from "effect/unstable/ai";

export const HelloPromptLive = Layer.mergeAll(
  McpServer.prompt({
    name: "hello",
    description: "Greet a person and introduce the MCP server",
    parameters: {
      name: Schema.String.pipe(
        Schema.annotate({
          description: "The name of the person to greet",
        }),
      ),
    },
    content: ({ name }) =>
      Effect.succeed(\`Hello, \${name}! Welcome to the Stack Effect MCP server.\`),
  }),
);
`;

export const mcpPrimerResourceContents = `import { Effect, Layer } from "effect";
import { McpServer } from "effect/unstable/ai";

export const PrimerResourceLive = Layer.mergeAll(
  McpServer.resource({
    uri: "stack-effect://primer",
    name: "Stack Effect Primer",
    description: "A short introduction to this generated MCP server",
    mimeType: "text/plain",
    content: Effect.succeed(
      "This MCP server was generated by Stack Effect and can be extended with tools, prompts, and resources.",
    ),
  }),
);
`;
