server {
    listen ${CLIENT_PORT};
    listen [::]:${CLIENT_PORT} default ipv6only=on;
    # /usr/share/nginx/html;
    root /app;
    index index.html;
    server_name _; # all hostnames
    location / {
        try_files $uri $uri/ /index.html =404;
    }
}
